include ../inc/make.inc

TOP=example_top
BD_SOURCE = zynq_ps_bd.tcl
HDL_SOURCE = $(TOP).sv
CONSTRAINTS =  ../inc/artyz7.xdc
DEVICE=xc7z020clg400-1
DEVICE_SHORT=xc7z020_1

# DEBUG_NETS = debug_nets.tcl

include ../inc/make.hw
